---
# --------------------------------

- name: "HandlerGrafanaReload"
  ansible.builtin.systemd:
    name: "{{ grafana_svc_name }}.service"
    state: reloaded
  become: true

- name: "HandlerGrafanaRestart"
  ansible.builtin.systemd:
    name: "{{ grafana_svc_name }}.service"
    state: restarted
  become: true

# --------------------------------
...
